In [1]:
# Demos functionality of the save_load_model_parameters module
# To execute, move this .ipynb file to the root folder
import save_load_model_parameters
import torch

In [2]:
# Create some dummy objects to save parameters from
dummy_module = torch.nn.Linear(in_features=5, out_features=3)
dummy_optimizer = torch.optim.Adam(dummy_module.parameters(), lr=3.14)

In [3]:
# We can see the parameters which will be saved to a file wtth .state_dict
dummy_module.state_dict(), dummy_optimizer.state_dict()

(OrderedDict([('weight',
               tensor([[-0.1858, -0.0283,  0.1094,  0.3646,  0.0810],
                       [ 0.2257, -0.4112,  0.2516, -0.0552, -0.3183],
                       [-0.0974, -0.2699, -0.1971, -0.2375,  0.0078]])),
              ('bias', tensor([0.1548, 0.3654, 0.4432]))]),
 {'state': {},
  'param_groups': [{'lr': 3.14,
    'betas': (0.9, 0.999),
    'eps': 1e-08,
    'weight_decay': 0,
    'amsgrad': False,
    'maximize': False,
    'foreach': None,
    'capturable': False,
    'differentiable': False,
    'fused': None,
    'params': [0, 1]}]})

In [4]:
# Save the parameters to an output file
file_name_module = "module_test"
module_save_success = save_load_model_parameters.save_parameters(module_or_optimizer=dummy_module, file_name=file_name_module, overwrite=True)

file_name_optimizer = "optimizer_test"
optimizer_save_success = save_load_model_parameters.save_parameters(module_or_optimizer=dummy_optimizer, file_name=file_name_optimizer, overwrite=True)

module_save_success, optimizer_save_success

(True, True)

In [5]:
# Now we can recall the model parameters from their files

# First, create new objects to load our parameters into
load_module = torch.nn.Linear(in_features=5, out_features=3)
load_optimizer = torch.optim.Adam(dummy_module.parameters(), lr=0.001)

# We can see the states of these objects after creation with.state_dict() again:
load_module.state_dict(), load_optimizer.state_dict()

(OrderedDict([('weight',
               tensor([[-0.1769, -0.2175, -0.3600, -0.1630, -0.0784],
                       [ 0.1794,  0.2874, -0.1988, -0.0282, -0.2725],
                       [ 0.0269, -0.0912, -0.1837, -0.1496,  0.4255]])),
              ('bias', tensor([ 0.1043, -0.1002,  0.1690]))]),
 {'state': {},
  'param_groups': [{'lr': 0.001,
    'betas': (0.9, 0.999),
    'eps': 1e-08,
    'weight_decay': 0,
    'amsgrad': False,
    'maximize': False,
    'foreach': None,
    'capturable': False,
    'differentiable': False,
    'fused': None,
    'params': [0, 1]}]})

In [6]:
# Now we can recall the parameters from our saved files into the new objects
module_load_success = save_load_model_parameters.load_parameters(module_or_optimizer=load_module, file_name=file_name_module)

optimizer_load_success = save_load_model_parameters.load_parameters(module_or_optimizer=load_optimizer, file_name=file_name_optimizer)

module_load_success, optimizer_load_success

(True, True)

In [7]:
# We can see that our module weights/bias and optimizer learning rate have been successfully
# updated to match the original values from the dummy objects
dummy_module.state_dict(), load_module.state_dict(), dummy_optimizer.state_dict(), load_optimizer.state_dict()

(OrderedDict([('weight',
               tensor([[-0.1858, -0.0283,  0.1094,  0.3646,  0.0810],
                       [ 0.2257, -0.4112,  0.2516, -0.0552, -0.3183],
                       [-0.0974, -0.2699, -0.1971, -0.2375,  0.0078]])),
              ('bias', tensor([0.1548, 0.3654, 0.4432]))]),
 OrderedDict([('weight',
               tensor([[-0.1858, -0.0283,  0.1094,  0.3646,  0.0810],
                       [ 0.2257, -0.4112,  0.2516, -0.0552, -0.3183],
                       [-0.0974, -0.2699, -0.1971, -0.2375,  0.0078]])),
              ('bias', tensor([0.1548, 0.3654, 0.4432]))]),
 {'state': {},
  'param_groups': [{'lr': 3.14,
    'betas': (0.9, 0.999),
    'eps': 1e-08,
    'weight_decay': 0,
    'amsgrad': False,
    'maximize': False,
    'foreach': None,
    'capturable': False,
    'differentiable': False,
    'fused': None,
    'params': [0, 1]}]},
 {'state': {},
  'param_groups': [{'lr': 3.14,
    'betas': (0.9, 0.999),
    'eps': 1e-08,
    'weight_decay': 0,
    'amsgr

In [8]:
# One last note, save_parameters() and load_parameters() will both return False if they fail due to
# a file not existing or not being able to be overwritten

# File already exists and overwrite=False
module_save_success = save_load_model_parameters.save_parameters(module_or_optimizer=dummy_module, file_name=file_name_module, overwrite=False)

# File doesn't exist
module_load_success = save_load_model_parameters.load_parameters(module_or_optimizer=load_module, file_name="not_a_file")

module_save_success, module_load_success

(False, False)